"""Initial migration.

Revision ID: 063bf9cba92c
Revises: 
Create Date: 2021-07-20 23:11:58.092627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063bf9cba92c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rssfeed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_url', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('last', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rssfeed_feed_url'), 'rssfeed', ['feed_url'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rssfeed_feed_url'), table_name='rssfeed')
    op.drop_table('rssfeed')
    # ### end Alembic commands ###
